steps:
# 1) Build Docker image with :latest tag
  - name: gcr.io/cloud-builders/docker
    id: "build-image"
    args:
      - build
      - -f
      - app/Dockerfile
      - -t
      - us-central1-docker.pkg.dev/${_PROJECT_ID}/my-repo/myapp:latest
      - app

  # 2) Push image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    id: "push-image"
    args:
      - push
      - "us-central1-docker.pkg.dev/${_PROJECT_ID}/my-repo/myapp:latest"

  # Get GKE credentials so kubectl can talk to the cluster
  - name: gcr.io/cloud-builders/gcloud
    id: "get-credentials"
    args:
      - container
      - clusters
      - get-credentials
      - ${_CLUSTER_NAME}
      - --region=${_REGION}
      - --project=${_PROJECT_ID}

  # Restart rollout so pods get recreated and pull :latest
  - name: gcr.io/cloud-builders/kubectl
    id: "rollout-restart"
    args:
      - rollout
      - restart
      - deployment/myapp
      - --namespace=default

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT_ID: "devops-gke-12345"
  _REGION: "us-east1"
  _CLUSTER_NAME: "devops-gke-cluster"
